# remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "Galaxy Raiders"
description: "This app is based on the 1978 game Space Invaders, with a twist. Being able to save progress and customize ships and weapons."
author:
  name: "Austin West"
  
theme: jekyll-theme-midnight
